import "dotenv/config";
import { randomUUID } from "node:crypto";
import { expect, test } from "@playwright/test";

test("可选作品信息框、诠释者编辑、讨论失效锚点与搜索回复定位", async ({ page }) => {
  test.setTimeout(120_000);
  const signed = await page.request.post("/api/auth/sign-in/email", { data: { email: process.env.SEED_ADMIN_EMAIL, password: process.env.SEED_ADMIN_PASSWORD } });
  expect(signed.ok()).toBe(true);
  const title = `MVP ${randomUUID()}`;
  const create = async (data: object) => {
    const response = await page.request.post("/api/submissions", { data });
    expect(response.status()).toBe(201); return response.json();
  };
  const term = await create({ kind: "new_term", title, content: "通俗正文" });
  await page.goto(term.href);
  await expect(page.getByText("关键文本", { exact: true })).toHaveCount(0);
  await page.getByRole("link", { name: "编辑词条信息", exact: true }).click();
  await page.getByRole("button", { name: "添加作品" }).click();
  await page.getByLabel("作品名 1", { exact: true }).fill("第一部作品");
  await page.getByRole("button", { name: "添加作品" }).click();
  await page.getByLabel("作品名 2", { exact: true }).fill("第二部作品");
  await page.getByRole("button", { name: "上移", exact: true }).nth(1).click();
  await expect(page.getByText(/草稿已自动保存/)).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("作品名 1", { exact: true })).toHaveValue("第二部作品");
  await page.getByRole("button", { name: "提交（直接生效）", exact: true }).click();
  await page.getByRole("link", { name: "查看页面 →" }).click();
  await expect(page.locator("aside").filter({ hasText: "关键文本" })).toContainText("第二部作品第一部作品");
  const interpreter = await create({ kind: "new_interpreter", title: `Reader ${title}` });
  await page.goto(interpreter.href);
  await page.getByRole("link", { name: "编辑诠释者信息" }).click();
  await page.getByRole("button", { name: "添加作品" }).click();
  await page.getByLabel("作品名 1", { exact: true }).fill("诠释者代表作品");
  await page.getByRole("button", { name: "提交（直接生效）", exact: true }).click();
  await page.getByRole("link", { name: "查看页面 →" }).click();
  await expect(page.locator("aside")).toContainText("诠释者代表作品");
  const perspective = await create({ kind: "new_perspective", termId: term.pageId, interpreterId: interpreter.pageId, content: "讨论的公开视角" });
  const floorResponse = await page.request.post("/api/discussion/posts", { data: { termId: term.pageId, perspectiveId: perspective.pageId, content: "已有讨论" } });
  expect(floorResponse.status()).toBe(201);
  const floor = await floorResponse.json();
  for (let i = 0; i < 12; i++) await page.request.post("/api/discussion/posts", { data: { termId: term.pageId, content: `填充楼层 ${i} ` + "讨论文字。".repeat(40) } });
  const needle = `uniquereply${Date.now()}`;
  const replyResponse = await page.request.post("/api/discussion/posts", { data: { termId: term.pageId, parentId: floor.id, content: needle } });
  expect(replyResponse.status()).toBe(201);
  const reply = await replyResponse.json();
  await page.goto(`/search?q=${needle}`);
  const hit = page.locator(`a[href$="#floor-${reply.id}"]`);
  await expect(hit).toBeVisible();
  await hit.click();
  await expect(page.locator(`#floor-${reply.id}`)).toContainText(needle);
  await expect(page.locator(`#floor-${reply.id}`)).toBeInViewport();
  expect((await page.request.post(`/api/admin/pages/${interpreter.pageId}`, { data: { action: "delete" } })).ok()).toBe(true);
  await page.reload();
  await expect(page.locator(`#floor-${floor.id}`).locator(`a[href="${perspective.href}"]`)).toHaveCount(0);
  expect((await page.request.post("/api/discussion/posts", { data: { termId: term.pageId, perspectiveId: perspective.pageId, content: "失效锚点" } })).status()).toBe(400);
  await page.request.post(`/api/admin/pages/${interpreter.pageId}`, { data: { action: "restore" } });
  await page.reload();
  await expect(page.locator(`#floor-${floor.id}`).locator(`a[href="${perspective.href}"]`)).toBeVisible();
});
